### ISSUE TITLE
Неправильное расположение Peak Marks

### ISSUE THREAD

**Issue by roman412** [roman412/Spectrum-Analyzer#1]
При выводе автоматически найденных пиков на кривую с отметками о пиках (peak marks), отметки расположены не на самих пиках, а смещены и сгруппированы в другом месте.

**Comment by Evshved** [comment]
Пробежавшись по дебагу, я не нашел бага. Только потом, я визуально начал догадываться о проблеме.

Проблема заключается в том, что найденные алгоритмически найденные пики в [данной ](https://github.com/roman412/Spectrum-Analyzer/blob/master/SpectrumAnalyzer/ViewModels/ViewModel.cs#L128) строке уже являются неправильными.

Проверил я это изменив маркер до [дефолтного](https://github.com/roman412/Spectrum-Analyzer/blob/master/SpectrumAnalyzer/Models/Plotter.cs#L150) плюс поставив ему значение размера дефолтное - 1.
```
MarkerSize = 1,
MarkerType = MarkerType.Circle,
```
Исходя из правильного выполнения [метода](https://github.com/roman412/Spectrum-Analyzer/blob/master/SpectrumAnalyzer/ViewModels/ViewModel.cs#L138) - маркер отрисовывается там, где находится указатель мышки при нажатии правой кнопки мыши, еще раз доказывает, что координата x в вышеприведенной функции передается некорректной.

**Comment by roman412** [comment]
Исправлено в fc14a3f.
Проблема была связана с неправильной работой функции-аггрегатора, предназначенной для поиска ближайшего бина, содержащего пик.
